# Generated by Django 5.2 on 2025-04-25 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='materials/previous_questions/')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='materials/notes/')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_text', models.TextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='materials/books/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materials/book_covers/')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materials.semester')),
            ],
        ),
    ]
