# Generated by Django 5.2 on 2025-04-24 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('academy', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('registration_link', models.URLField(blank=True, max_length=500, null=True)),
                ('registration_deadline', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('course_days', models.DurationField(default=datetime.timedelta(seconds=3600))),
            ],
        ),
    ]
